// export const cardList = [
//     { suit: "♠", value: "A", score: 11 },
//     { suit: "♠", value: "2", score: 2 },
//     { suit: "♠", value: "3", score: 3 },
//     { suit: "♠", value: "4", score: 4 },
//     { suit: "♠", value: "5", score: 5 },
//     { suit: "♠", value: "6", score: 6 },
//     { suit: "♠", value: "7", score: 7 },
//     { suit: "♠", value: "8", score: 8 },
//     { suit: "♠", value: "9", score: 9 },
//     { suit: "♠", value: "10", score: 10 },
//     { suit: "♠", value: "J", score: 10 },
//     { suit: "♠", value: "Q", score: 10 },
//     { suit: "♠", value: "K", score: 10 },
//     { suit: "♥", value: "A", score: 11 },
//     { suit: "♥", value: "2", score: 2 },
//     { suit: "♥", value: "3", score: 3 },
//     { suit: "♥", value: "4", score: 4 },
//     { suit: "♥", value: "5", score: 5 },
//     { suit: "♥", value: "6", score: 6 },
//     { suit: "♥", value: "7", score: 7 },
//     { suit: "♥", value: "8", score: 8 },
//     { suit: "♥", value: "9", score: 9 },
//     { suit: "♥", value: "10", score: 10 },
//     { suit: "♥", value: "J", score: 10 },
//     { suit: "♥", value: "Q", score: 10 },
//     { suit: "♥", value: "K", score: 10 },
//     { suit: "♦", value: "A", score: 11 },
//     { suit: "♦", value: "2", score: 2 },
//     { suit: "♦", value: "3", score: 3 },
//     { suit: "♦", value: "4", score: 4 },
//     { suit: "♦", value: "5", score: 5 },
//     { suit: "♦", value: "6", score: 6 },
//     { suit: "♦", value: "7", score: 7 },
//     { suit: "♦", value: "8", score: 8 },
//     { suit: "♦", value: "9", score: 9 },
//     { suit: "♦", value: "10", score: 10 },
//     { suit: "♦", value: "J", score: 10 },
//     { suit: "♦", value: "Q", score: 10 },
//     { suit: "♦", value: "K", score: 10 },
//     { suit: "♣", value: "A", score: 11 },
//     { suit: "♣", value: "2", score: 2 },
//     { suit: "♣", value: "3", score: 3 },
//     { suit: "♣", value: "4", score: 4 },
//     { suit: "♣", value: "5", score: 5 },
//     { suit: "♣", value: "6", score: 6 },
//     { suit: "♣", value: "7", score: 7 },
//     { suit: "♣", value: "8", score: 8 },
//     { suit: "♣", value: "9", score: 9 },
//     { suit: "♣", value: "10", score: 10 },
//     { suit: "♣", value: "J", score: 10 },
//     { suit: "♣", value: "Q", score: 10 },
//     { suit: "♣", value: "K", score: 10 },
// ]

//TODO: Remove temp short cardList
export const cardList = [
    { suit: "♠", value: "A", score: 11 },
    { suit: "♠", value: "A", score: 11 },
    { suit: "♠", value: "A", score: 11 },
    { suit: "♠", value: "A", score: 11 },
    { suit: "♠", value: "A", score: 11 },
    { suit: "♠", value: "A", score: 11 },
    { suit: "♠", value: "A", score: 11 },
    { suit: "♠", value: "A", score: 11 },
    { suit: "♠", value: "2", score: 2 },
    { suit: "♠", value: "3", score: 3 },
    { suit: "♠", value: "4", score: 4 },
    { suit: "♠", value: "5", score: 5 },
    { suit: "♠", value: "6", score: 6 },
    { suit: "♠", value: "7", score: 7 },
    { suit: "♠", value: "8", score: 8 },
    { suit: "♠", value: "9", score: 9 },
    { suit: "♠", value: "10", score: 10 },
    { suit: "♠", value: "J", score: 10 },
    { suit: "♠", value: "Q", score: 10 },
    { suit: "♠", value: "K", score: 10 },

]